
--create db
CREATE DATABASE TWITTERSENT;
COMMIT;

--create table TWITTER_USR for user account details
CREATE TABLE TWITTER_USR 
(
USR_ID INT PRIMARY KEY NOT NULL,
USR_NM VARCHAR(255),
TWITTER_USR_NM VARCHAR(255)
);
COMMIT;

--create table TWEETS for tweets
CREATE TABLE TWEETS
(
TWEET_ID SERIAL,
USR_ID INT,
TWEET_TEXT VARCHAR(255),
CREATED_AT TIMESTAMP,
PRIMARY KEY (TWEET_ID),
FOREIGN KEY (USR_ID) REFERENCES TWITTER_USR (USR_ID)
);
COMMIT;