
--create db
CREATE DATABASE TWITTERSENT;
COMMIT;

--create table TWITTER_USR for user account details
CREATE TABLE TWITTER_USR 
(
USR_ID VARCHAR(255) PRIMARY KEY NOT NULL,
USR_NM VARCHAR(255),
TWITTER_USR_NM VARCHAR(255)
);
COMMIT;

--drop table TWEETS;
--create table TWEETS for tweets
/*CREATE TABLE TWEETS
(
TWEET_ID SERIAL,
USR_ID VARCHAR(255),
TOPICS VARCHAR(255),
TWEET_TEXT VARCHAR(255),
CREATED_AT TIMESTAMP,
PRIMARY KEY (TWEET_ID),
FOREIGN KEY (USR_ID) REFERENCES TWITTER_USR (USR_ID)
);
COMMIT;*/


--drop table TWEETS_HAZE;
--create table TWEETS_HAZE for tweets
CREATE TABLE TWEETS_HAZE
(
TWEET_ID SERIAL,
USR_ID VARCHAR(255),
TOPICS VARCHAR(255),
TWEET_TEXT VARCHAR(255),
CREATED_AT TIMESTAMP,
PRIMARY KEY (TWEET_ID),
FOREIGN KEY (USR_ID) REFERENCES TWITTER_USR (USR_ID)
);
COMMIT;